//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from CARL.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="CARLParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface ICARLListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="CARLParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] CARLParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CARLParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] CARLParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CARLParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] CARLParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CARLParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] CARLParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CARLParser.equalityExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEqualityExpression([NotNull] CARLParser.EqualityExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CARLParser.equalityExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEqualityExpression([NotNull] CARLParser.EqualityExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CARLParser.relationExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelationExpression([NotNull] CARLParser.RelationExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CARLParser.relationExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelationExpression([NotNull] CARLParser.RelationExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CARLParser.binaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBinaryExpression([NotNull] CARLParser.BinaryExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CARLParser.binaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBinaryExpression([NotNull] CARLParser.BinaryExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CARLParser.multExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultExpression([NotNull] CARLParser.MultExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CARLParser.multExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultExpression([NotNull] CARLParser.MultExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CARLParser.unaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnaryExpression([NotNull] CARLParser.UnaryExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CARLParser.unaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnaryExpression([NotNull] CARLParser.UnaryExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CARLParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTerm([NotNull] CARLParser.TermContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CARLParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTerm([NotNull] CARLParser.TermContext context);
}
